import router from '../../util/router.js';
import collectRefs from '../../util/collectRefs.js';
import emptyNode from '../../util/emptyNode.js';

// components
import '../app-icon/app-icon.js';
import '../app-card/app-card.js';
import '../loading-bar/loading-bar.js';
import '../search-result/search-result.js';
import '../movie-box/movie-box.js';

// styles
import appStyles from './movies-app.less';
import globalStyles from './global.less';

// generate style tag for global css rules
const globalStyleTag = document.createElement('style');

// inject styles generated by css loader
globalStyleTag.textContent = globalStyles.toString();

const template = `
  <style>${ appStyles.toString() }</style>
  <loading-bar></loading-bar>
  <header>
    <h1>Movies</h1>
    <div ref="subtitle"></div>
  </header>
  <main class="view" ref="view"></main>
`;

class MoviesApp extends HTMLElement {
  constructor() {
    super();

    this.attachShadow({ mode: 'open' });
    this.shadowRoot.innerHTML = template;

    // append global styles
    document.body.insertBefore(globalStyleTag, this);

    // create subtitles aot
    this.homeSubtitle = document.createElement('h2');
    this.homeSubtitle.textContent = 'Look up fast information about your favorite titles';

    this.movieSubtitle = document.createElement('h2');
    this.movieSubtitle.innerHTML = `
      <span class=${ appStyles.locals.back }>
        <app-icon type="back"></app-icon> Back to Search
    `;

    this.movieSubtitle.addEventListener('click', e => {
      router.navigate('/');
    });
  }

  connectedCallback() {
    // get refs
    collectRefs.call(this);

    // router config
    // movie route
    router.on('/movie/:id', (params) => {
      this.renderMovie(params.id);
    });

    // home route
    router.on('/', () => {
      this.renderHome();
    });

    // wild card route
    router.on('*', () => {
      this.renderHome();
    });

    // resolve current url
    router.resolve();
  }

  renderHome() {
    emptyNode(this.refs.subtitle);
    this.refs.subtitle.insertBefore(this.homeSubtitle, null);
    this.refs.view.innerHTML = `<app-card hollow><search-result title="Batman" year="1989" mid="268"></search-result></app-card>`;
  }

  renderMovie(id) {
    emptyNode(this.refs.subtitle);
    this.refs.subtitle.insertBefore(this.movieSubtitle, null);
    this.refs.view.innerHTML = `<movie-box mid="${ id }"></movie-box>`;
  }
}

window.customElements.define('movies-app', MoviesApp);
